@extends('layouts.master')

@section('content')
    <div id="product">
        <div class="row">
            <div class="col-xs-12">
                {{--<h4>{{ $title }}</h4>--}}

                <form>

                    <legend>New Part Order</legend>

                    <div class="form-group col-xs-6">
                        <label for="inputClaimNumber">Part Order #</label>
                        <input type="text" class="form-control" id="inputClaimNumber" placeholder="This will be autogenerated from DB">
                    </div>

                    <div class="form-group col-xs-6">
                        <label for="inputClaimNumber">Associated Claim</label>
                        <input type="text" class="form-control" id="inputClaimNumber" placeholder="This will be provided by the claim">
                    </div>

                    <legend>Parts</legend>

                    <div class="form-group col-xs-6">
                        <label for="inputClaimNumber">Part #</label>
                        <input type="text" class="form-control" id="inputClaimNumber" placeholder="">
                    </div>

                    <div class="form-group col-xs-6">
                        <label for="inputClaimNumber">Quantity</label>
                        <input type="text" class="form-control" id="inputClaimNumber" placeholder="">
                    </div>

                    <div class="col-xs-12 text-center">
                        <button class="btn btn-lg btn-primary">+ Add Another Part</button>
                    <div>

                    <br /><br />
                    <div class="form-group col-xs-12">
                        <label for="inputClaimNumber">Comments</label>
                        <input type="text" class="form-control" id="inputClaimNumber" placeholder="For the first comment - more can be added later">
                    </div>

                    <br /><br />
                    <button type="submit" class="btn btn-primary col-xs-12">Submit</button>
                </form>
                
            </div>
        </div>
    </div>
@endsection